spring.application.name=accounts_module
server.port=8081
#spring.security.enabled=false
#spring.security.user.name=none
#spring.security.user.password=none

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://database-2.cfo8igmmq0km.us-east-2.rds.amazonaws.com:3306/boa?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Logging level
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
